/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.cadastro;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.bean.Cliente;
import model.bean.Endereco;
import model.dao.ClienteDAO;
import model.dao.MolduraDAO;

/**
 *
 * @author Felipe
 */
public class CadFornecedor extends javax.swing.JInternalFrame {
    private List<String> listaTelefone;
    private List<Endereco> listaEndereco;
    private int idTelCel;
    private int rowContatos;
    private int rowEnderecos;
    private String maskCpf;
    private String maskCnpj;
    private String maskInscEstadual;
    private String maskTel;
    private String maskCel;
    
    /**
     * Creates new form CadCliente
     */
    public CadFornecedor() {
        initComponents();
        this.idTelCel = 0;
        this.listaEndereco = new ArrayList<>();
        this.listaTelefone = new ArrayList<>();
        this.rowContatos = -1;
        this.rowEnderecos = -1;
        this.cboxUf.setSelectedIndex(12);//MG
        this.edtCidade.setText("Ubá");
        
        this.maskCnpj = this.edtCnpj.getText();
        this.maskInscEstadual = this.edtInscEstadual.getText();
        this.maskCel = this.edtCelular.getText();
        this.maskTel = this.edtTelefone.getText();
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        edtNome = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        edtCnpj = new javax.swing.JFormattedTextField();
        edtInscEstadual = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        edtEmail = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cboxUf = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        edtCidade = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        edtBairro = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        edtRua = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        edtComplemento = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        edtNumero = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        edtReferencia = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaEnderecos = new javax.swing.JTable();
        btnAddEndereco = new javax.swing.JButton();
        btnRemoveEndereco = new javax.swing.JButton();
        btnEditEndereco = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelaContatos = new javax.swing.JTable();
        edtTelefone = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        edtDescricao = new javax.swing.JTextField();
        btnAdicionarNumero = new javax.swing.JButton();
        btnRemoverNumero = new javax.swing.JButton();
        edtCelular = new javax.swing.JFormattedTextField();
        jLabel16 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnCadastrar = new javax.swing.JButton();
        btnLimparDados = new javax.swing.JButton();

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro de Fornecedor");

        jLabel8.setText("Nome:");

        jLabel11.setText("CNPJ: ");

        try {
            edtCnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        edtCnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtCnpjActionPerformed(evt);
            }
        });

        try {
            edtInscEstadual.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        edtInscEstadual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtInscEstadualActionPerformed(evt);
            }
        });

        jLabel12.setText("Insc. Estadual: ");

        jLabel13.setText("E-mail: ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(228, 228, 228)
                        .addComponent(jLabel13))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(edtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(edtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(227, 227, 227)
                        .addComponent(jLabel12))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(edtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(137, 137, 137)
                        .addComponent(edtInscEstadual, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel13))
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(edtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11))
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtInscEstadual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Endereços"));

        jLabel2.setText("UF:");

        cboxUf.setModel(new javax.swing.DefaultComboBoxModel<>(this.uf()));
        cboxUf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxUfActionPerformed(evt);
            }
        });

        jLabel3.setText("Cidade:");

        jLabel4.setText("Bairro");

        jLabel5.setText("Rua: ");

        jLabel6.setText("Complemento:");

        jLabel7.setText("Numero:");

        jLabel14.setText("Referência:");

        edtReferencia.setColumns(20);
        edtReferencia.setRows(5);
        jScrollPane1.setViewportView(edtReferencia);

        tabelaEnderecos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cidade", "Bairro", "Rua", "Numero", "Complemento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaEnderecos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaEnderecosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabelaEnderecos);

        btnAddEndereco.setBackground(new java.awt.Color(31, 132, 61));
        btnAddEndereco.setText("Adicionar Endereço");
        btnAddEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEnderecoActionPerformed(evt);
            }
        });

        btnRemoveEndereco.setBackground(new java.awt.Color(250, 95, 99));
        btnRemoveEndereco.setText("Remover Endereço");
        btnRemoveEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveEnderecoActionPerformed(evt);
            }
        });

        btnEditEndereco.setBackground(new java.awt.Color(68, 144, 196));
        btnEditEndereco.setText("Editar Endereço");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(edtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(edtRua, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(cboxUf, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(edtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel5))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(edtComplemento, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                            .addComponent(edtBairro)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAddEndereco)
                        .addGap(18, 18, 18)
                        .addComponent(btnRemoveEndereco)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditEndereco)))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboxUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edtRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(edtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddEndereco)
                            .addComponent(btnRemoveEndereco)
                            .addComponent(btnEditEndereco))
                        .addGap(0, 14, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tabelaContatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Número", "Descrição"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaContatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaContatosMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tabelaContatos);

        try {
            edtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        edtTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtTelefoneActionPerformed(evt);
            }
        });

        jLabel9.setText("Telefone:");

        jLabel15.setText("Descrição");

        btnAdicionarNumero.setBackground(new java.awt.Color(31, 132, 61));
        btnAdicionarNumero.setText("Adicionar");
        btnAdicionarNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarNumeroActionPerformed(evt);
            }
        });

        btnRemoverNumero.setBackground(new java.awt.Color(250, 95, 99));
        btnRemoverNumero.setText("Remover");
        btnRemoverNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverNumeroActionPerformed(evt);
            }
        });

        try {
            edtCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) # ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        edtCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtCelularActionPerformed(evt);
            }
        });

        jLabel16.setText("Celular:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(edtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(81, 81, 81))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(edtDescricao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAdicionarNumero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemoverNumero))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdicionarNumero)
                    .addComponent(btnRemoverNumero)
                    .addComponent(edtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        btnCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones PNG/1486564412-plus_81511.png"))); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnLimparDados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones PNG/broom.png"))); // NOI18N
        btnLimparDados.setText("Limpar Dados");
        btnLimparDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparDadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCadastrar)
                .addGap(18, 18, 18)
                .addComponent(btnLimparDados)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar)
                    .addComponent(btnLimparDados))
                .addGap(0, 47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void edtCnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtCnpjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtCnpjActionPerformed

    private void edtInscEstadualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtInscEstadualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtInscEstadualActionPerformed

    private void edtTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtTelefoneActionPerformed

    private void edtCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtCelularActionPerformed
     
    private boolean isCamposVazios() {//apenas os campos necessários, nome,telefone/celular,e um endereço
        boolean flag = false;
        
        if(this.edtNome.getText().isEmpty()){
            flag = true;
            JOptionPane.showMessageDialog(null, "O Campo 'Nome' está vazio!", "Atenção", JOptionPane.WARNING_MESSAGE);
        }else if(listaTelefone.isEmpty()){
            flag = true;
            JOptionPane.showMessageDialog(null, "Insira um número de telefone ou celular para concluir o cadastro", "Atenção", JOptionPane.WARNING_MESSAGE);
        }else if(this.listaEndereco.isEmpty()){
            flag = true;
            JOptionPane.showMessageDialog(null, "Insira um endereço para concluir o cadastro", "Atenção", JOptionPane.WARNING_MESSAGE);
        }
        return flag;
    }
    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        
        if(this.isCamposVazios()==false){
            Cliente c = new Cliente();
            
            
            if(!this.edtCnpj.getText().equals(maskCnpj)){
                c.setCnpj(this.edtCnpj.getText());
            }
           
            if(!this.edtInscEstadual.getText().equals(maskInscEstadual)){
               c.setInscEstadual(this.edtInscEstadual.getText()); 
            }
            c.setEmail(this.edtEmail.getText());
            
            c.setListaTelefone(this.listaTelefone);
            c.setListaEndereco(this.listaEndereco);
            
            ClienteDAO dao = new ClienteDAO();
            dao.salvar(c);
        }
        
        
    }//GEN-LAST:event_btnCadastrarActionPerformed
    private String removeMask(String str){
        str = str.replace("(", "");
        str = str.replace(")", "");
        str = str.replace("/", "");
        str = str.replace("-", "");
        str = str.replace(".", "");
        str = str.replace(",", "");
        str = str.replace(" ", "");
        return str;
    }
    
    private void btnAdicionarNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarNumeroActionPerformed
        DefaultTableModel modelTable = (DefaultTableModel) this.tabelaContatos.getModel();

        String tel = "";
        String cel = "";
        String desc = "";
        String registro = "";
        String aux = "";
        
        aux = this.removeMask(this.edtTelefone.getText());
        System.out.println(aux+"<<<aux");
        if(aux.length() ==10){
            tel = this.edtTelefone.getText();
            desc = this.edtDescricao.getText();
            registro = tel+";"+desc+";";
            
            System.out.println(registro);
            
            this.listaTelefone.add(registro);
            if(idTelCel == 0){
                idTelCel =1;
            }
            modelTable.addRow(new Object[]{idTelCel,tel,desc});
            idTelCel++;
        }else if(aux.length() < 10 && aux.length() > 0){
            System.out.println("***********");
            JOptionPane.showMessageDialog(null, "Numero de telefone deve ter 10 digitos ex: (32)4455-6677");
        }else{
            System.out.println(aux.length());
        }
        
       
        aux = this.removeMask(this.edtCelular.getText());
        if(aux.length() == 11){
            System.out.println("////");
            cel = this.edtCelular.getText();
            desc = this.edtDescricao.getText();
            registro = cel+";"+desc+";";
            this.listaTelefone.add(registro);
            
            if(idTelCel == 0){
                idTelCel =1;
            }
            
            modelTable.addRow(new Object[]{idTelCel,cel,desc});
            idTelCel++;
        }else if(aux.length() < 11 && aux.length() > 0){
            JOptionPane.showMessageDialog(null, "Numero de celular deve ter 11 digitos ex: (32)9 4455-6677");
        }
        
        this.edtTelefone.setText("");
        this.edtCelular.setText("");
        this.edtDescricao.setText("");
    }//GEN-LAST:event_btnAdicionarNumeroActionPerformed

    private void btnRemoverNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverNumeroActionPerformed
        DefaultTableModel modelTable = (DefaultTableModel) this.tabelaContatos.getModel();
        if(this.rowContatos != -1){
            JOptionPane.showMessageDialog(null, "Contato "+modelTable.getValueAt(rowContatos, 1)+" Removido");
            modelTable.removeRow(rowContatos);
            this.listaTelefone.remove(this.rowContatos);
            this.rowContatos = -1;
        }else{
            JOptionPane.showMessageDialog(null, "Selecione uma linha para excluir!", "Atenção", JOptionPane.WARNING_MESSAGE);
            
        }
                
    }//GEN-LAST:event_btnRemoverNumeroActionPerformed

    private void tabelaContatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaContatosMouseClicked
        this.rowContatos = this.tabelaContatos.getSelectedRow();
    }//GEN-LAST:event_tabelaContatosMouseClicked

    private boolean isCamposEnderecoVazios(){
        boolean flag = false;
        
        if(this.edtCidade.getText().isEmpty()){
            flag = true;
            JOptionPane.showMessageDialog(null, " O Campo 'Cidade' está vazio!", "Atenção", JOptionPane.WARNING_MESSAGE);
        }else if(this.edtBairro.getText().isEmpty()){
            flag = true;
            JOptionPane.showMessageDialog(null, "O Campo 'Bairro' Está Vazio!", "Atenção", JOptionPane.WARNING_MESSAGE);
        }else if(this.edtRua.getText().isEmpty()){
            flag = true;
            JOptionPane.showMessageDialog(null, " O Campo 'Rua' está vazio!", "Atenção", JOptionPane.WARNING_MESSAGE);
        }else if(this.edtNumero.getText().isEmpty()){
            flag = true;
            JOptionPane.showMessageDialog(null, " O Campo 'Número' está vazio!", "Atenção", JOptionPane.WARNING_MESSAGE);
        }
        return flag;
    }
    
    private boolean isCamposEnderecosVazios(){
        boolean flag = false;
        
        if(this.edtCidade.getText().isEmpty()){
            flag = true;
            JOptionPane.showMessageDialog(null, " O Campo 'Cidade' está vazio!", "Atenção", JOptionPane.WARNING_MESSAGE);
        }else if(this.edtBairro.getText().isEmpty()){
            flag = true;
            JOptionPane.showMessageDialog(null, " O Campo 'Bairro' está vazio!", "Atenção", JOptionPane.WARNING_MESSAGE);
        }else if(this.edtRua.getText().isEmpty()){
            flag = true;
            JOptionPane.showMessageDialog(null, " O Campo 'Rua' está vazio!", "Atenção", JOptionPane.WARNING_MESSAGE);
        }else if(this.edtNumero.getText().isEmpty()){
            flag = true;
            JOptionPane.showMessageDialog(null, " O Campo 'Número' está vazio!", "Atenção", JOptionPane.WARNING_MESSAGE);
        }
        
        return flag;
    }
    private void btnAddEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEnderecoActionPerformed
        DefaultTableModel modelTable = (DefaultTableModel) this.tabelaEnderecos.getModel();
        
        if(this.isCamposEnderecosVazios() == false){
            Endereco endereco = new Endereco();
            
            endereco.setUf(this.cboxUf.getSelectedItem().toString());
            endereco.setCidade(this.edtCidade.getText());
            endereco.setBairro(this.edtBairro.getText());
            endereco.setRua(this.edtRua.getText());
            endereco.setComplemento(this.edtComplemento.getText());
            endereco.setNumero(this.edtNumero.getText());
            endereco.setReferencia(this.edtReferencia.getText());
            
            this.listaEndereco.add(endereco);
            
            modelTable.addRow(new Object[]{
                endereco.getCidade(),
                endereco.getBairro(),
                endereco.getRua(),
                endereco.getNumero(),
                endereco.getComplemento() 
            });
        }
    }//GEN-LAST:event_btnAddEnderecoActionPerformed

    private void cboxUfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxUfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxUfActionPerformed

    private void tabelaEnderecosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaEnderecosMouseClicked
        this.rowEnderecos = this.tabelaEnderecos.getSelectedRow();
    }//GEN-LAST:event_tabelaEnderecosMouseClicked
    
    private void limparCamposEndereco(){
        this.cboxUf.setSelectedIndex(12);
        this.edtCidade.setText("Ubá");
        this.edtBairro.setText("");
        this.edtRua.setText("");
        this.edtComplemento.setText("");
        this.edtNumero.setText("");
        this.edtReferencia.setText("");
    }
    private void btnRemoveEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveEnderecoActionPerformed
        DefaultTableModel modelTable = (DefaultTableModel) this.tabelaEnderecos.getModel();
        
        if(this.rowEnderecos != -1){
            modelTable.removeRow(this.rowEnderecos);
          
            this.listaEndereco.remove(this.rowEnderecos);
            this.limparCamposEndereco();
            this.rowEnderecos = -1;
        }
    }//GEN-LAST:event_btnRemoveEnderecoActionPerformed
    private void limparDadosCabecalho(){
        this.edtNome.setText("");
        
        this.edtEmail.setText("");
        this.edtInscEstadual.setText("");   
        this.edtCnpj.setText("");
        this.edtTelefone.setText("");
        this.edtCelular.setText("");
    }
    
    private void limparTabela(JTable tabela){
        DefaultTableModel modelTable = (DefaultTableModel) tabela.getModel();
        modelTable.setNumRows(0);
    }
    private void btnLimparDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparDadosActionPerformed
        this.limparDadosCabecalho();
        this.limparCamposEndereco();
        limparTabela(this.tabelaContatos);
        limparTabela(this.tabelaEnderecos);
        
    }//GEN-LAST:event_btnLimparDadosActionPerformed

    private String[] uf(){
       return new String[]{"AC","AL","AP","AM","BA","CE","DF","ES","GO","MA","MT","MS","MG","PA","PB","PR","PE",
                            "PI","RJ","RN","RS","RO","RR","SC","SP","SE","TO"};
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddEndereco;
    private javax.swing.JButton btnAdicionarNumero;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnEditEndereco;
    private javax.swing.JButton btnLimparDados;
    private javax.swing.JButton btnRemoveEndereco;
    private javax.swing.JButton btnRemoverNumero;
    private javax.swing.JComboBox<String> cboxUf;
    private javax.swing.JTextField edtBairro;
    private javax.swing.JFormattedTextField edtCelular;
    private javax.swing.JTextField edtCidade;
    private javax.swing.JFormattedTextField edtCnpj;
    private javax.swing.JTextField edtComplemento;
    private javax.swing.JTextField edtDescricao;
    private javax.swing.JTextField edtEmail;
    private javax.swing.JFormattedTextField edtInscEstadual;
    private javax.swing.JTextField edtNome;
    private javax.swing.JTextField edtNumero;
    private javax.swing.JTextArea edtReferencia;
    private javax.swing.JTextField edtRua;
    private javax.swing.JFormattedTextField edtTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tabelaContatos;
    private javax.swing.JTable tabelaEnderecos;
    // End of variables declaration//GEN-END:variables

    public List<String> getListaTelefone() {
        return listaTelefone;
    }

    public void setListaTelefone(List<String> listaTelefone) {
        this.listaTelefone = listaTelefone;
    }

    public List<Endereco> getListaEndereco() {
        return listaEndereco;
    }

    public void setListaEndereco(List<Endereco> listaEndereco) {
        this.listaEndereco = listaEndereco;
    }

   
}
