/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.cadastro;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.bean.Vidro;
import model.dao.FornecedorDAO;
import model.dao.VidroDAO;

/**
 *
 * @author Felipe
 */
public class CadVidro extends javax.swing.JInternalFrame {

    private List<Vidro> listaVidro;
    
    public CadVidro() {
        initComponents();
        try {
            listaVidro = new VidroDAO().load();
            this.tabelaLoad();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CadVidro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private String formatoStringDouble(String str){
        Pattern pattern = Pattern.compile("[.^]");
        Matcher matcher = pattern.matcher(str);
        if(matcher.find()){
            str = str.replace(".", "");
        }
        str = str.replace(",", ".");
        return str;
    }
    
    private boolean isCamposPreenchidos(){
        boolean flag = true;
        
        if(this.edtTipo.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "O Campo 'Tipo' Está Vazio", "ATENÇÃO", JOptionPane.INFORMATION_MESSAGE);
            flag = false;
        }else if(this.edtAltura.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "O Campo 'Altura Chapa' Está Vazio", "ATENÇÃO", JOptionPane.INFORMATION_MESSAGE);
            flag = false;
        }else if(this.edtComprimento.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "O Campo 'Comprimento Chapa' Está Vazio", "ATENÇÃO", JOptionPane.INFORMATION_MESSAGE);
            flag = false;
        }else if(this.edtPrecoCusto.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "O Campo 'Preço Custo' Está Vazio", "ATENÇÃO", JOptionPane.INFORMATION_MESSAGE);
            flag = false;
        }else if(this.spinEspessura.getValue().equals(0)){
            JOptionPane.showMessageDialog(null, "O Campo 'Espessura' Não Foi Especificado", "ATENÇÃO", JOptionPane.INFORMATION_MESSAGE);
            flag = false;
        }else if(this.spinQtd.getValue().equals(0)){
            JOptionPane.showMessageDialog(null, "O Campo 'Quantidade Chapas' Não Foi Especificado", "ATENÇÃO", JOptionPane.INFORMATION_MESSAGE);
            flag = false;
        }
        return flag;
    }

    private void tabelaLoad(){
        DefaultTableModel modelTable = (DefaultTableModel) this.tabela.getModel();
        modelTable.setNumRows(0);
        
        for(Vidro v: this.listaVidro){
            modelTable.addRow(new Object[]{
                v.getId(),
                v.getTipo(),
                v.getAlturaChapa(),
                v.getComprimentoChapa(),
                v.getEspessuraChapa(),
                v.getQuantidadeChapas(),
                v.getPrecoCusto()
            });
        }
    
    }
    
    private void limparCampos(){
        this.edtTipo.setText("");
        this.edtAltura.setText("");
        this.edtComprimento.setText("");
        this.edtPrecoCusto.setText("");
        this.spinEspessura.setValue(0);
        this.spinQtd.setValue(0);
        this.cboxFornecedor.setSelectedIndex(0);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        edtTipo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        spinQtd = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        btnCadastrar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        btnLimparCampos = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cboxFornecedor = new javax.swing.JComboBox<>();
        spinEspessura = new javax.swing.JSpinner();
        edtPrecoCusto = new javax.swing.JFormattedTextField();
        edtAltura = new javax.swing.JFormattedTextField();
        edtComprimento = new javax.swing.JFormattedTextField();

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro de Chapa de Vidro");

        jLabel3.setText("Tipo");

        jLabel4.setText("Altura Chapa");

        jLabel6.setText("Preço Custo");

        jLabel5.setText("Comprimmento Chapa ");

        jLabel7.setText("m²");

        jLabel9.setText("Quantidade Chapas");

        jLabel11.setText("Espessura ");

        jLabel12.setText("mm");

        jLabel14.setText("m");

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Tipo", "Altura", "Comprimento", "Espessura", "Qtd", "Preço Custo"
            }
        ));
        jScrollPane2.setViewportView(tabela);

        btnCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones PNG/1486564412-plus_81511.png"))); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones PNG/diskette.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones PNG/lixo.png"))); // NOI18N
        btnExcluir.setText("Excluir");

        jLabel15.setText("m");

        btnLimparCampos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones PNG/broom.png"))); // NOI18N
        btnLimparCampos.setText("Limpar Campos");
        btnLimparCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparCamposActionPerformed(evt);
            }
        });

        jLabel8.setText("Fornecedor");

        cboxFornecedor.setModel(new javax.swing.DefaultComboBoxModel<>(this.listaFornecedor()));
        cboxFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxFornecedorActionPerformed(evt);
            }
        });

        edtPrecoCusto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));

        edtAltura.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        edtComprimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(edtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(edtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel15)
                        .addGap(27, 27, 27)
                        .addComponent(edtComprimento, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel14))
                    .addComponent(jLabel8)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(104, 104, 104)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(spinEspessura, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(jLabel12)
                                .addGap(11, 11, 11)
                                .addComponent(edtPrecoCusto, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(jLabel7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel6)))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(spinQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCadastrar)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimparCampos))
                    .addComponent(cboxFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSalvar)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluir)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1029, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(edtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edtComprimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel14))))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(jLabel9)))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spinEspessura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edtPrecoCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spinQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel7))))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addGap(6, 6, 6)
                        .addComponent(cboxFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 218, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnExcluir)
                    .addComponent(btnLimparCampos)
                    .addComponent(btnCadastrar))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimparCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparCamposActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimparCamposActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        if(this.isCamposPreenchidos()){
            Vidro v = new Vidro();
            String aux = "";
            
            v.setTipo(this.edtTipo.getText());
            
            aux = formatoStringDouble(this.edtAltura.getText());
            v.setAlturaChapa(Double.parseDouble(aux));
            
            aux = formatoStringDouble(this.edtComprimento.getText());
            v.setComprimentoChapa(Double.parseDouble(aux));
            
            aux = formatoStringDouble(this.edtPrecoCusto.getText());
            v.setPrecoCusto(Double.parseDouble(aux));
            
            v.setQuantidadeChapas((int)this.spinQtd.getValue());
            v.setEspessuraChapa((int)this.spinEspessura.getValue());
            
            FornecedorDAO fDao = new FornecedorDAO();
            
            try {
                v.setFornecedorCnpj(fDao.getCnpj(this.cboxFornecedor.getSelectedItem().toString()));
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(CadVidro.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "ERRO CadVidro - "+ex);
            }
            
            
            VidroDAO dao = new VidroDAO();
            
            try {
                dao.salvar(v);
                this.listaVidro = dao.load();
                this.tabelaLoad();
                this.limparCampos();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(CadVidro.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void cboxFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxFornecedorActionPerformed

    private String[] listaFornecedor(){
        FornecedorDAO dao = new FornecedorDAO();
        String[] list = null;
        try {
            list = dao.getNomeFornecedor();
            if(list.length <1 ){//Sem ter o registro padrao "Não"
                JOptionPane.showMessageDialog(null, "ERRO - O sistema não achou Fornecedores registrados no Banco de Dados ");
                String aux = "Sem Registro;";
                list = aux.split(";");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CadMoldura.class.getName()).log(Level.SEVERE, null, ex);
        }
        return list;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimparCampos;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cboxFornecedor;
    private javax.swing.JFormattedTextField edtAltura;
    private javax.swing.JFormattedTextField edtComprimento;
    private javax.swing.JFormattedTextField edtPrecoCusto;
    private javax.swing.JTextField edtTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner spinEspessura;
    private javax.swing.JSpinner spinQtd;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
