/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.busca;

import connection.ConnectionFactory;
import java.awt.Color;
import java.awt.Component;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.ParseException;
import java.util.List;
import javax.swing.JFormattedTextField;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;
import model.dao.NotaDAO;
/**
 *
 * @author Felipe
 */
public class BuscarNota extends javax.swing.JInternalFrame {

    /**
     * Creates new form BuscarNota
     */
    public BuscarNota() {
        initComponents();
        this.rbCrescente.setSelected(true);
        this.edtValorDeBusca1.setEnabled(false);
    }

    public String[] vetBuscarPor(){
        String[] vet = {"","Nome do Cliente","Numero da Nota","CPF","CNPJ","Insc. Estadual","E-mail","Telefone"};
        return vet;
    }
    
    
    
    public String whereSQL(){
        /*
            Definindo a primeira variável WHERE para a realização da QUERY do comando a baixo:
        
            SELECT n.id,cn.nome, n.valor_total,n.data_da_nota,n.data_entrega,
            t.numero, ns.status_pagamento, cc.cpf,cnpj.cnpj,cInsc.insc_estadual,cm.email
            FROM nota AS n left JOIN nota_cliente as nc ON nc.id_nota = n.id
            left JOIN cliente_nome AS cn ON nc.id_cliente = cn.id
            left join nota_status AS ns on ns.id = n.id
            left join telefone as t on t.id = cn.id 
            left join cliente_cpf AS cc ON cc.id = cn.id
            left join cliente_cnpj AS cnpj ON cnpj.id = cn.id
            left join cliente_insc_estadual AS cInsc ON cInsc.id = cn.id
            left join cliente_email AS cm ON cm.id = cn.id
            where ? = ?;
        */
        String where = "";
           switch(this.cboxProcurarPor.getSelectedIndex()){
                case 0:
                   break;
                case 1:
                    where = "cn.nome";
                    break;
                case 2:
                    where = "n.id";
                    break;
                case 3:
                    where = "cc.cpf";
                    break;
                case 4:
                    where = "cnpj.cnpj";
                    break;
                case 5:
                    where = "cInsc.insc_estadual";
                    break;
                case 6:
                    where = "t.numero";
                    break;
                default:
                    System.out.println("Erro ao definir a clausula WHERE na sintax da busca SQL");
           }
        return where;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        rbCrescente = new javax.swing.JRadioButton();
        rbDecrescente = new javax.swing.JRadioButton();
        edtValorDeBusca1 = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        cboxProcurarPor = new javax.swing.JComboBox<>();
        checkBoxSelectAll = new javax.swing.JCheckBox();
        edtValorDeBusca = new javax.swing.JFormattedTextField();

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Buscar Nota");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Nota", "Nome", "Telefone", "Valor Total", "Data de Emissão", "Data de Entrega", "Status do Pgto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        table.setRequestFocusEnabled(false);
        table.setRowHeight(50);
        table.setShowGrid(false);
        jScrollPane1.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(2).setPreferredWidth(100);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
        );

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones PNG/zenmap_104119.png"))); // NOI18N
        jButton4.setText("Visualizar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones PNG/file-complete256_25223.png"))); // NOI18N
        jButton5.setText("Finalizar");

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones PNG/file-edit_114433.png"))); // NOI18N
        jButton12.setText("Editar Registro");

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones PNG/pdf (1).png"))); // NOI18N
        jButton13.setText("Gerar PDF");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton5)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jButton12)
                .addGap(18, 18, 18)
                .addComponent(jButton13)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton12)
                    .addComponent(jButton13))
                .addGap(25, 25, 25))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel11.setText("Procurar Por:");

        jLabel12.setText("Ordenar Por:");

        rbCrescente.setText("Crescente");
        rbCrescente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbCrescenteMouseClicked(evt);
            }
        });

        rbDecrescente.setText("Decrescente");
        rbDecrescente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbDecrescenteMouseClicked(evt);
            }
        });

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        cboxProcurarPor.setModel(new javax.swing.DefaultComboBoxModel<>(this.vetBuscarPor()));
        cboxProcurarPor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboxProcurarPorItemStateChanged(evt);
            }
        });

        checkBoxSelectAll.setText("Todos");
        checkBoxSelectAll.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkBoxSelectAllItemStateChanged(evt);
            }
        });
        checkBoxSelectAll.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                checkBoxSelectAllStateChanged(evt);
            }
        });
        checkBoxSelectAll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkBoxSelectAllMouseClicked(evt);
            }
        });

        edtValorDeBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtValorDeBuscaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(cboxProcurarPor, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(602, 602, 602))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbCrescente)
                            .addComponent(rbDecrescente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(edtValorDeBusca1, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                            .addComponent(edtValorDeBusca))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(checkBoxSelectAll)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPesquisar)
                        .addGap(88, 88, 88))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(4, 4, 4)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbCrescente)
                    .addComponent(edtValorDeBusca1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar)
                    .addComponent(cboxProcurarPor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkBoxSelectAll))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbDecrescente)
                    .addComponent(edtValorDeBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        NotaDAO nDAO = new NotaDAO();
        DefaultTableModel modelTable = (DefaultTableModel) this.table.getModel();
        List<Object[]> lista;
        try {
            modelTable.setNumRows(0);
            boolean orderBy;
            if(this.rbCrescente.isSelected()){
                orderBy = true;
            }else{
                orderBy = false;
            }
            lista = nDAO.buscarNota(whereSQL(), this.edtValorDeBusca1.getText(),this.checkBoxSelectAll.isSelected(),orderBy);
            
            for(int i = 0; i<lista.size();i++){
                modelTable.addRow(lista.get(i));
            }
            //table.setRowHeight(100);
            updateRowHeights();
        } catch (ClassNotFoundException ex) {
            
            Logger.getLogger(BuscarNota.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void checkBoxSelectAllItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkBoxSelectAllItemStateChanged
        
    }//GEN-LAST:event_checkBoxSelectAllItemStateChanged

    private void checkBoxSelectAllStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_checkBoxSelectAllStateChanged
        
    }//GEN-LAST:event_checkBoxSelectAllStateChanged

    private void checkBoxSelectAllMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkBoxSelectAllMouseClicked
        if(this.checkBoxSelectAll.isSelected()){
            this.cboxProcurarPor.setSelectedIndex(0);
            this.cboxProcurarPor.setEnabled(false);
            this.edtValorDeBusca1.setText("");
            this.edtValorDeBusca1.setEditable(false);
            this.checkBoxSelectAll.setForeground(Color.red);
            this.edtValorDeBusca1.setBackground(Color.lightGray);
        }else{
            this.edtValorDeBusca1.setEditable(true);
            this.cboxProcurarPor.setEnabled(true);
            this.edtValorDeBusca1.setBackground(Color.white);
            this.checkBoxSelectAll.setForeground(Color.black);
        }
    }//GEN-LAST:event_checkBoxSelectAllMouseClicked

    private void rbCrescenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbCrescenteMouseClicked
        if(this.rbCrescente.isSelected()){
            this.rbDecrescente.setSelected(false);
        }  
    }//GEN-LAST:event_rbCrescenteMouseClicked

    private void rbDecrescenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbDecrescenteMouseClicked
        if(this.rbDecrescente.isSelected()){
            this.rbCrescente.setSelected(false);
        }
    }//GEN-LAST:event_rbDecrescenteMouseClicked

    private void cboxProcurarPorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboxProcurarPorItemStateChanged
       this.edtValorDeBusca1.setText("");
       if(cboxProcurarPor.getSelectedIndex()== 0){
           this.edtValorDeBusca1.setEnabled(false);
           this.edtValorDeBusca1.setText("");
       }else{
           this.edtValorDeBusca1.setEnabled(true);
       }
       
        try {
            switch(this.cboxProcurarPor.getSelectedIndex()){

            case 0:
            case 1:
            case 2:
               
                break;
            case 3:
                MaskFormatter mask = new MaskFormatter();
                
                
                System.out.println("DEU CERTO");
                break;
            case 4:
                break;
            case 5:
                break;
            case 6:
                break;

            }
        } catch (Exception e) {
        }
  
    }//GEN-LAST:event_cboxProcurarPorItemStateChanged

    private void edtValorDeBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtValorDeBuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtValorDeBuscaActionPerformed

    private void updateRowHeights()
    {
        for (int row = 0; row < table.getRowCount(); row++)
        {
            int rowHeight = table.getRowHeight();

            for (int column = 0; column < table.getColumnCount(); column++)
            {
                Component comp = table.prepareRenderer(table.getCellRenderer(row, column), row, column);
                rowHeight = Math.max(rowHeight, comp.getPreferredSize().height);
            }

            table.setRowHeight(row, rowHeight);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JComboBox<String> cboxProcurarPor;
    private javax.swing.JCheckBox checkBoxSelectAll;
    private javax.swing.JFormattedTextField edtValorDeBusca;
    private javax.swing.JTextField edtValorDeBusca1;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbCrescente;
    private javax.swing.JRadioButton rbDecrescente;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
